// swifttex-wasm/svelte/SwiftTeX.svelte
<script>
    import { render } from '../pkg/swifttex.js';

    export let tex = '';
    export let className = '';
    export let style = '';
    export let displayMode = false;
    export let fontSize = undefined;
    export let output = undefined;
    export let mathStyle = undefined;
    export let inlineFonts = undefined;

    let innerHTML = '';
    let isError = false;

    $: {
        const options = {
            display_mode: displayMode,
            font_size: fontSize,
            output: output,
            math_style: mathStyle,
            inline_fonts: inlineFonts
        };

        // Remove undefined fields
        Object.keys(options).forEach(key => options[key] === undefined && delete options[key]);

        try {
            const result = render(tex, options);
            if (result.svg && result.mathml) {
                innerHTML = result.mathml + result.svg;
            } else if (result.svg) {
                innerHTML = result.svg;
            } else if (result.mathml) {
                innerHTML = result.mathml;
            }
            isError = false;
        } catch (e) {
            innerHTML = String(e);
            isError = true;
        }
    }
</script>

{#if displayMode}
    <div class="swifttex-container {className}" style="{style}{isError ? '; color: red;' : '; display: block;'}">
        {@html innerHTML}
    </div>
{:else}
    <span class="swifttex-container {className}" style="{style}{isError ? '; color: red;' : '; display: inline-block;'}">
        {@html innerHTML}
    </span>
{/if}

// swifttex-wasm/examples/react/SwiftTeX.jsx
import { useEffect, useRef, useState } from "react";

export function SwiftTeX({ tex, displayMode = false, fontSize = 16 }) {
  const [result, setResult] = useState(null);
  const wasmRef = useRef(null);

  useEffect(() => {
    import("swifttex").then(wasm => {
      wasmRef.current = wasm;
      const out = wasm.render(tex, { display_mode: displayMode, font_size: fontSize });
      setResult(out);
    });
  }, [tex, displayMode, fontSize]);

  if (!result) return null;
  if (result.error) return <span style={{ color: "red" }}>{result.error}</span>;
  return (
    <span
      style={{ display: displayMode ? "block" : "inline-block" }}
      dangerouslySetInnerHTML={{ __html: result.svg }}
    />
  );
}
